[package]
name = "cg_ultimate_tic_tac_toe"
version = "0.2.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
my_lib = { path = "../../mylib" }